### PR TITLE
Anomalies visible on Cesium map

### PR DESCRIPTION
**Pull request by shrew97**
Solved issues #7 , #8 , #14

Fetches anomalies from a realtime database and marks the anomalies with a different color when they're new or something changed in the database (doesn't need to be a color change, but some sort of user notification is required). Anomaly description available when anomaly is pressed (as well as a box that shows that anomaly is targeted). Red circle that displays our data-boundary so our users know where it's "common" for anomalies to dissapear and reappear. Locked camera zoom and location.

### CODE REVIEW

**Comment by jvikstrom** [comment]
So this is way to unwieldy to actually do a code review of. Just add a script that runs linting on travis and when it passes the travis build the PR will be approved.

(You'd have to add a line to .travis.yml at line 7 that runs the shell script for linting)

This for instance is how the script that runs linting for the backend looks like:
`
#!/bin/sh
cd backend;

if gulp eslint; 
then
    echo "Passed linting"
else
    exit 1;
fi


if gulp test;
then
    echo "Passed linting"
else
    exit 1;
fi
`

Line 6 runs the shell script for linting and testing the backend. Do something similar for the frontend.

If you've got npm on the frontend you could just use gulp and eslint (requires a gulpfile. look at backend/gulpfile.js), otherwise I've got no idea :)

**Comment by shrew97** [comment]
I'll try to get it working with Cesium. It says on the pull request though that it passed both Travis tests, isn't that the same thing? Other than that there's only really two scripts you need to look at (should have specified that), in cesium_frontend/Apps/scripts/app.js and cesium_frontend/Apps/scripts/firebase_app.js

**Comment by jvikstrom** [comment]
Well currently no tests are run for the frontend on travis, you need to add linting for it

**Review by jvikstrom — CHANGES_REQUESTED** [review]
You have some code that is commented out in App.js, remove it instead of putting it in a comment, otherwise I think it looks good.

**Comment by shrew97** [comment]
Removed that code snippet 👍 Squashed it with the most recent commit

**Comment by shrew97** [comment]
Lint errors are now fixed, I am now a lint god.

**Review by jvikstrom — APPROVED** [review]

**Comment by jvikstrom** [comment]
@shrew97 sorry for being super slow with merging.

**Pull request merged**
